services:
  backend:
    image: ghcr.io/nghoangquan175/wettenhalls-backend:latest
    container_name: wettenhalls-backend
    restart: unless-stopped
    # ports:
    #   - "5000:5000"
    networks:
      - wettenhalls-net
    env_file:
      - ./backend/.env.production
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 450M
        reservations:
          memory: 128M

  frontend:
    image: ghcr.io/nghoangquan175/wettenhalls-frontend:latest
    container_name: wettenhalls-frontend
    restart: unless-stopped
    # ports:
    #   - "3000:80"
    networks:
      - wettenhalls-net
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 32M
    depends_on:
      backend:
        condition: service_healthy
